# Generated by Django 3.1.1 on 2020-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0002_auto_20200908_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='user_image'),
        ),
    ]
