# Generated by Django 3.1.1 on 2020-09-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0003_userdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
