# Generated by Django 3.1.1 on 2020-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0004_auto_20200928_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.CharField(max_length=100),
        ),
    ]
