# Generated by Django 3.1.1 on 2020-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0006_tweet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
    ]
