# Generated by Django 3.1.1 on 2020-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0007_remove_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(height_field=460, null=True, upload_to='user_image', width_field=450),
        ),
    ]
