# Generated by Django 3.1.1 on 2020-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0008_auto_20201001_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='user_image'),
        ),
    ]
