# Generated by Django 3.1.1 on 2020-10-21 05:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0009_auto_20201001_1039'),
    ]


    operations = [
        TrigramExtension(), BtreeGinExtension()
    ]