# Generated by Django 3.1.1 on 2020-10-21 05:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0010_auto_20201021_0555'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user', 'content'], name='minitwitter_user_id_a001c2_gin'),
        ),
    ]
